services:
  mysql-db:
    container_name: mysql
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: larvel
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent localhost:3306 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3
