services:
  db:
    container_name: mysql-quanthub-dev
    image: mysql:8.2.0
    networks:
      - quanthub-default
    volumes:
      - quanthub-mysql-data:/var/lib/mysql
      - quanthub-mysql-conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 33306:3306
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent localhost:3306 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

networks:
  quanthub-default:
    driver: bridge
    name: quanthub-default

volumes:
  quanthub-mysql-data:
    name: quanthub-mysql-data
  quanthub-mysql-conf:
    name: quanthub-mysql-conf

