services:
  mysql-db:
    container_name: mysql-quanthub-prod
    image: mysql:8.2.0
    networks:
      - quanthub-prod-network
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - quanthub-mysql-conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quanthub
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent localhost:3306 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

  es01:
    container_name: es01-quanthub-prod
    image: elasticsearch:8.14.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - quanthub-prod-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -I http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
    command: >
      /bin/bash -c "
      /usr/local/bin/docker-entrypoint.sh eswrapper &
      while ! curl -s http://localhost:9200; do sleep 1; done;
      curl -X PUT 'http://localhost:9200/quanthub-articles' -H 'Content-Type: application/json' -d '{\"settings\": {\"number_of_shards\": 1, \"number_of_replicas\": 1}}';
      curl -X PUT 'http://localhost:9200/quanthub-announcements' -H 'Content-Type: application/json' -d '{\"settings\": {\"number_of_shards\": 1, \"number_of_replicas\": 1}}';
      wait"

  kibana:
    container_name: kibana-quanthub-prod
    image: kibana:8.14.1
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    healthcheck:
      test: [ "CMD-SHELL", "curl -I http://localhost:5601 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      es01:
        condition: service_healthy
    networks:
      - quanthub-prod-network

  redis:
    container_name: redis-quanthub-prod
    image: redis:7.2.5
    volumes:
      - ./redis/data:/root/redis
      - quanthub-redis:/usr/local/etc/redis
    environment:
      - REDIS_PASSWORD=
      - REDIS_DATABASES=16
    networks:
      - quanthub-prod-network
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 3
    command: redis-server --requirepass .....

  quanthub-backend:
    container_name: quanthub-backend
    image: leopoldhsing2/quanthub-backend
    environment:
      - ELASTICSEARCH_HOST=es01-quanthub-prod:9200
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-quanthub-prod
      - DB_PORT=
      - DB_DATABASE=quanthub
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - REDIS_CLIENT=predis
      - REDIS_HOST=redis-quanthub-prod
      - REDIS_PASSWORD=1234
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_CACHE_DB=1
      - APP_NAME=QuantHub
      - APP_ENV=production
      - APP_KEY=
      - APP_DEBUG=true
      - APP_TIMEZONE=UTC
      - APP_URL=https://quanthub.discobroccoli.com
    depends_on:
      es01:
        condition: service_healthy
      mysql-db:
        condition: service_healthy
    command: >
      /bin/sh -c "
      php artisan setup:elasticsearch &&
      php artisan migrate --force &&
      php artisan serve --host=0.0.0.0 --port=8000
      "
    networks:
      - quanthub-prod-network
  quanthub-frontend:
    container_name: quanthub-frontend
    image: leopoldhsing2/quanthub-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_AUTH0_DOMAIN=
      - VITE_AUTH0_CLIENT_ID=
      - VITE_AUTH0_CALLBACK_URL=https://quanthub.discobroccoli.com
      - VITE_AUTH0_AUDIENCE=quanthub-api
      - VITE_BASE_URL=https://quanthub.discobroccoli.com:12345
    depends_on:
      - quanthub-backend
    networks:
      - quanthub-prod-network

networks:
  quanthub-prod-network:
    driver: bridge
    name: quanthub-prod-network

volumes:
  quanthub-mysql-conf:
    name: quanthub-mysql-conf
  quanthub-redis:
    name: quanthub-redis
