services:
  mysql-db:
    container_name: mysql-quanthub-prod
    image: mysql:8.2.0
    networks:
      - quanthub-prod-network
    volumes:
      - quanthub-mysql-data:/var/lib/mysql
      - quanthub-mysql-conf:/etc/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent localhost:3306 >/dev/null || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 3

  es01:
    container_name: es01-quanthub-prod
    image: elasticsearch:8.14.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      # enable SSL
      # - xpack.security.enabled=true
      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.transport.ssl.verification_mode=certificate
      # - xpack.security.transport.ssl.key=/path/to/your/certificate.key
      # - xpack.security.transport.ssl.certificate=/path/to/your/certificate.crt
      # - xpack.security.transport.ssl.certificate_authorities=/path/to/your/ca.crt
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - quanthub-prod-network
    healthcheck:
      test: [ "CMD-SHELL", "curl -I http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
  kibana:
    container_name: kibana-quanthub-prod
    image: kibana:8.14.1
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    healthcheck:
      test: [ "CMD-SHELL", "curl -I http://localhost:5601 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      es01:
        condition: service_healthy
    networks:
      - quanthub-prod-network

  redis:
    container_name: redis-quanthub-prod
    image: redis:7.2.5
    volumes:
      - ./redis/data:/root/redis
      - quanthub-redis:/usr/local/etc/redis
    environment:
      - REDIS_PASSWORD=1234
      - REDIS_DATABASES=16
    networks:
      - quanthub-prod-network
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 3
    command: redis-server --requirepass 1234

  quanthub-frontend:
    container_name: quanthub-frontend
    image: quanthub-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_AUTH0_DOMAIN=dev-gjuz7abiktxqva10.us.auth0.com
      - VITE_AUTH0_CLIENT_ID=YnSRNfRB977e35vBiBsWLUYVGbOGQZBU
      - VITE_AUTH0_CALLBACK_URL=https://quanthub.discobroccoli.com
      - VITE_AUTH0_AUDIENCE=quanthub-api
      - VITE_BASE_URL=http://quanthub-backend:8000
      - VITE_AWS_ACCESSKEY_ID=AKIA47CRX226HYDYOWDQ
      - VITE_AWS_SECRET_ACCESSKEY=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
      - VITE_S3_BUCKET_NAME=quanthub-rrc
      - VITE_S3_REGION=ca-central-1
  quanthub-backend:
    container_name: quanthub-backend
    image: quanthub-backend
    environment:
      - ELASTICSEARCH_HOST=es01-quanthub-prod:9200
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-quanthub-prod
      - DB_PORT=3306
      - DB_DATABASE=quanthub
      - DB_USERNAME=root
      - DB_PASSWORD=1234
      - REDIS_CLIENT=predis
      - REDIS_HOST=redis-quanthub-prod
      - REDIS_PASSWORD=1234
      - REDIS_PORT=16379
      - REDIS_DB=0
      - REDIS_CACHE_DB=1
      - APP_NAME=QuantHub
      - APP_ENV=local
      - APP_KEY=base64:cSK+ChUmACtjieWWi6bTxT8tzx5oRI4UlGrmnx9556E=
      - APP_DEBUG=true
      - APP_TIMEZONE=UTC
      - APP_URL=http://localhost

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - quanthub-frontend
      - quanthub-backend
    networks:
      - rrc-default-network

networks:
  quanthub-prod-network:
    driver: bridge
    name: quanthub-prod-network

volumes:
  quanthub-mysql-data:
    name: quanthub-mysql-data
  quanthub-mysql-conf:
    name: quanthub-mysql-conf

